# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    namespace: nextcloud
type: Opaque
stringData:
    adminUsername: ENC[AES256_GCM,data:drGJpY60QkbQeg==,iv:OdvrWka0QL9baWLy8sH85ZMjpWGnWdcqAVjlZEatylo=,tag:N3ZQFLw/j/x2J58Mf2F3Qw==,type:str]
    adminPassword: ENC[AES256_GCM,data:xSfN9oVlisil7wbJGQjzQEtfHOs=,iv:DKCXAeoUcObUQubVlG3Pu+jXkPpuNYjtzvPRDhs13js=,tag:v4JkeE7FuvDGpeZwA6dHaQ==,type:str]
    dbUsername: ENC[AES256_GCM,data:aybTsDGqmcqz,iv:TDE83gbUUpObUbrnV0bLRi7nZWOFNAprpAli1eZK6kM=,tag:HACvoRqBZf9ksOVij7MJsg==,type:str]
    dbName: ENC[AES256_GCM,data:QPeFjkWuwjPk,iv:fYCtkYWHyVMpziYlNmY0qUVcneqXDqFfVvbLUjnR8A0=,tag:VsIfnlyyK5D530yX3Vw/9Q==,type:str]
    dbPassword: ENC[AES256_GCM,data:pSinPhLxh8ZMn5fiiTXiQXIO,iv:64oiUi7m5cWbrhRFnETWa6uK5civU5MhtaJvF1VovzI=,tag:bSnmXVjNlNBw4hmyc7DHOA==,type:str]
    dbRootPassword: ENC[AES256_GCM,data:nQBtMXxrLmHNBTIAePf+YPw60Eoa,iv:WLwqYqkSxXUc9fQzbP8Z1jN2qIG4OSQEvjKVqSgRnXQ=,tag:KecUDX4XgeVcenDOJWjoHA==,type:str]
    redisPassword: ENC[AES256_GCM,data:g2PrJQ==,iv:FapjnUQTJgDsNgbcOiD3XY8TA5Dx09AtbGpIACA168o=,tag:kjUYCpX95c850T/9g/xczA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jcp34flxzy6rhx5wtpusfu6g8h2vafuy06cc7kduv9nq75pzvqgs2exz82
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVWg2cDFkbDY4Skx2cUNN
            T05IMHplOUlzclFwNHZrSzZ1UFdSWEdFRkVVCmhJeE10a3NKeUVaWWxvaGsyY2hy
            dUhIakozY0gzZ3BxZWs2RWNEZmNJeVEKLS0tIE8wYmdaeWVMejNjWWkxblZnMmxM
            bGdXNC9qY2g2SjZxdFYwR3hPQzNBT0kKjPrC5lcGkC1zemQUOwKWn4QuqUmD8Ffg
            2dC2f66qPTk6dwQ6oKxvQIJElwsnvSM7lZde5jAsAKTRH8p6toOvIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-07T16:20:39Z"
    mac: ENC[AES256_GCM,data:kvwugEYmm7IPI/kSXjI0ktEjiG2xQWs0ZrGRUsIUPp/0WRc967A8VOXMzPqqMpfANAIwnHw9TDr8fclcqJePDQ12pBW/aJYBypcc7OxbnVUNAq8c8MMmMGeGSGuJLWLwVASZaFe/1dXB4MCUv7SmcVrTu8n4u6RMLTRfaYabajc=,iv:QULgCEDigGeAW19Vli0icSPApK60mWaDq4oDxaAwuFQ=,tag:wojbrDvmuENnV0hV6c3wWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
