---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app redis
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      version: 17.4.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      imageRegistry: public.ecr.aws
      storageClass: truenas-ssd-nvmeof
    auth:
      enabled: false
      sentinel: false
      # existingSecret: *app
    master:
      persistence:
        enabled: false
      resources:
        requests:
          cpu: 15m
          memory: 20Mi
        limits:
          memory: 50Mi
    replica:
      persistence:
        enabled: false
      resources:
        requests:
          cpu: 15m
          memory: 20Mi
        limits:
          memory: 50Mi
    commonConfiguration: |-
      # Enable AOF https://redis.io/topics/persistence#append-only-file
      appendonly yes
      # Disable RDB persistence, AOF persistence already enabled.
      save ""
    sentinel:
      enabled: true
      masterSet: redis-master
      getMasterTimeout: 10
      startupProbe:
        failureThreshold: 2
      persistence:
        enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
