apiVersion: v1
kind: Secret
metadata:
    name: truenas-config-nfs
    namespace: storage
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:YqTnjwfuA0FVw1+Dd4uO67bbqfdAKhXrfEa0+/YPbM7h7cibHZDlj1DEm8N4N1edxtl6+HCyTPHzVwwKkTrAjwD/bJZueWaCJgGBMl1ZCJUaWpTPNsDdZL+mbHH82ETFGXISpfMAnYG3pKfs9Z/N5l+4DnnEqNWsxF3bCh/j3417pepvU+ccEN/Iuu9ZSCoPAvgaZSGa8i0U//2P2hd4hd4NgqAJgX/aYkwbV5rTqUz4b87ZuNnA4fKoyyN5WhemVmNC/oqKpcza+yllrh9TE2Jjzs0TtOfSnl57GHU9v/L3VriW51UBvGKhMXbFIw/GV3fE9AZcRkmybPOF49HwrstJ1pYkhI9YpLKkABVesUoGTl4LlAzTORn9hkyNZxVDRXb5BMZhjpbAMnXaOZWZv/FRR8iMzxMzFXnmqiwEcXdmvhJYYXc/txzvafy466sXyjX5khwMWHw5MvfbG64UKzrNnwUr8KjBlY6LiCtHU1B88K7jDWTSFGgdHRLc/ibrVKtvlOcoJPtJiEgJUOzZBk5w6sdwLs5d6KW9BP5/bTKLfpxAXE8i9zFSrTPRzWJ2Ob8rYA9hqqb34I12jJWEMHa6wGJ/VM/UJDEGsRiGmnU+Owl+FUsDKnbX+KjHbexpcBv/rkZeIpLpyR6/DfvGu5Exev6NQa5YRiExTN8eFqW+FdOpI0HWskwAnTIlV4/HBdzK56WNWR7QUSM1TlmkgXscEUSkD9zuFKROUHFFZIis8CdSNYwmtHDCqSY7tk79vxYdEB1QTkwZ7ksqS86Ac4i9FsCgzbo6jo9FCTWlOZZGAJROu35fX3VpN/A1f+rjh1uFytyfP68bCouOat3poE3wYlOo19feo/jcl5VqGr1B2hr6C3QaJn83p3xQsQXpGP0DZ8YYwlRzwNHdIM8WrbAXbOXEwCCFiko3rtu9qjZU7R8vfq64wre+iOJGwlNejTRpoB4eEjNnoVBq5jNZTU5ucndtJAMo6XZBYd7vWQ6y5v4nWzJTJGqeROP+MNqxZrvRO4JtYLsrcw==,iv:SZxv4UiyMoCWcGPaLTJ1UEr95j+gsicf6nRBO9Kmwe4=,tag:GSBRJtxNnBodKki9mRuHzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jcp34flxzy6rhx5wtpusfu6g8h2vafuy06cc7kduv9nq75pzvqgs2exz82
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeWdvaUNGSE5QTzdUSEFq
            am5lakR1UmtMWnlqQ1ZLRFV3WG81MDArK0dBClovK3U5YU5MQTRXcmJGRmhyZEpo
            SGhNQ3kxK0tkWHpkZCtvQm1ETUlkTW8KLS0tIE52YjZ1Q1pXN2huWnpML3pzT0dF
            ZjhHeCt3T0NOU3N0V0dBaXZWT2thV0UKbB5332q4r3GbpVbi7G2YcDKazoykMnoT
            t1IiGVwwPIZtzTW+6rcF+vk8p+Ke8euhpv4POS3YzCId4MlzO6SIvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-21T00:30:29Z"
    mac: ENC[AES256_GCM,data:VXSBs7slsOhdWM9nnlt9dkJCbyjoLaQGJPDikwPeL4WhPEg3kkQ5j72WNy9n0OF0wVWOwxRZ9yQGyvEX+fBr47A6k3tEolePXa4QK5Lkz1jx3RlvFQsGgbkqHoVsTgqklDlOvOF7Z7eADgg0K2iyJopa7OLET39a8fVCosoIsSo=,iv:I0t1XoavpN/7w2eUVizeUR9WMKv0hrN2ezXIgeS4+Qg=,tag:I4wXR5PieRx4HyhJETVxPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
