# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: prometheus-secrets
    namespace: monitoring
type: Opaque
stringData:
    minio_bearer_token: ENC[AES256_GCM,data:Qo8aGavYl8i+OBM4rDJwvbn/MMhtXnmklfyIBsfhDqfBhJ/npJxXQg/8rY460HpWefe8w0pPVAHbRdSrx+RB2CQ7p3jHYxvwzyc4tO994t6kXOECHD7V9QgHOkkHfBOv0uKulUeRbEM3lFKY3VhNE0+vCV7YKCRLTCWd7kulvIvjIXVHaZdLUBVSgROrR56LQw3VIrPK12bBEZWVj0joppi7xniHbqt8zGBl7VArVxjgahCbsvMqQeNBtPJQec151DfMvLnIZ9fgYDEBEcb8De1qMMg=,iv:2KQFJQ1tqLIfVbl0dMTIM6+xwM7D0mAQR6goVVDtCWg=,tag:9uSNn9i27A/T7+E6Lij9gA==,type:str]
    telegram_bot_token: ENC[AES256_GCM,data:oAWXLFvm8Z937T38wiJY3eiY7Q2sWcgreIEzABBLxlxin4jI/2bdtX0cqQOLmQ==,iv:AC546StxXAWncN4wW9HRzV//wrQ7/r234u/R4gx4E4k=,tag:xM18NKD5oA+eadqKdRtLHQ==,type:str]
    telegram_chat_id: ENC[AES256_GCM,data:NwEwHGXyIeP5,iv:7aT1n7WmFk/rQPC3VPKBNK1UpK/z02CNA2FTfrufg6I=,tag:EYxMe2TuFjNoihiuM86Kuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jcp34flxzy6rhx5wtpusfu6g8h2vafuy06cc7kduv9nq75pzvqgs2exz82
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMkw0dUVCR2NmaExJWVhU
            SWY3V1hMQ0lSNHE4MENNa2JiakFISGVjYW0wCnE3YzZmQXV2NEd1THBzMDNoT0xn
            MDRXMGYzYmhpN1BENExaYURsUmtKc2MKLS0tIHFhQnZRVzBIU2NnNGVGM1RNcm1S
            bjNJMDVmT2laNEVNbk4rbVBpSTB0dFkKqGvMxx0UnPlbJtSTNtMivFGm/bmUpRvH
            8/CSjojzD5o9mdukoFXmj61iEo4ieuYb7RAgnBrhCtrrmObQa3XLAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T10:58:37Z"
    mac: ENC[AES256_GCM,data:2Lun/eA723prWhGrHN8ZkkxMMKok4jOCrcljUIU68h2ob9nZMgMn+iqt3XZp2BW9MAltVGPVAyWP6Mlm9ll1wGljC3bZmeDWsK7ImJ2L4s3bXcf5hqf+lNMw2X0Gd/xhqUgjfgqe9xIzfCc333RhxLC3WqhcdC4TNR8etKBkY/A=,iv:wc/zB08exYXeP6RMMibjZYqiFZSPmSX4H7UCxYg/Ej4=,tag:AlSoKucWMhTYCO3BSMUKRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
