---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: rootnode
  namespace: networking
spec:
  myASN: 64502
  peerASN: 64500
  peerAddress: 192.168.1.1
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: rootnode-kubenet
  namespace: networking
spec:
  ipAddressPools:
    - kubenet-pool
