---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-v1
  namespace: database
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:14.6
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: truenas-ssd-nvmeof
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
  superuserSecret:
    name: postgres-superuser
  monitoring:
    enablePodMonitor: true

  # bootstrap:
  #   initdb:
  #     database: nextcloud
  #     owner: nextcloud
  #     secret:
  #       name: postgres-nextcloud

  # recovery:
  #  source: postgres

  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 4
      destinationPath: s3://postgres/
      endpointURL: https://s3.services.${SECRET_DOMAIN}:9000
      serverName: postgres-v1
      s3Credentials:
        accessKeyId:
          name: barman-postgres-secrets
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: barman-postgres-secrets
          key: MINIO_SECRET_KEY
