---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://democratic-csi.github.io/charts/
      chart: snapshot-controller
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-charts
        namespace: flux-system
  values:
    rbac:
      enabled: true

    controller:
      enabled: true
      image:
        repository: k8s.gcr.io/sig-storage/snapshot-controller
        tag: v6.1.0
      args:
        - "--v=5"
        - "--leader-election=true"

    validatingWebhook:
      enabled: false
      image:
        repository: k8s.gcr.io/sig-storage/snapshot-validation-webhook
        tag: v6.1.0